# Generated by Django 3.2.18 on 2023-04-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
